name: Fuzz

on:
  schedule:
    - cron: '0 8 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: latest

    - name: Build
      run: bash fuzz.sh
